update: 配置文件清单信息优化、xctl清单解析

diff --git a/xctl b/xctl
--- a/xctl
+++ b/xctl
@@ -5,6 +5,8 @@ set -o errexit
 
 SCRIPT_DIR=$(dirname "$0")
 SCRIPT_NAME=$(basename "$0")
+CONFIG_FILE=""
+INVENTORY_FILE=""
 
 cd ${SCRIPT_DIR} || exit 1
 
@@ -13,9 +15,11 @@ function usage() {
     cat <<EOF
 -------------------------------------------------------------------------------------
 Ansible SpringBoot OPS:
+    install     <config file>          to install same springboot application
     start       <config file>          to start same springboot application
     stop        <config file>          to stop same springboot application
-
+    restart     <config file>          to restart same springboot application
+    uninstall   <config file>          to uninstall same springboot application
 EOF
 }
 
@@ -25,24 +29,23 @@ function logger() {
     local SOURCE="\033[36m[$FNAME:${BASH_LINENO[0]}]\033[0m"
     case "$1" in
         debug)
-            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[36mDEBUG $2\033[0m"
+            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[36m[DEBUG] $2\033[0m"
             ;;
         info)
-            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[32mINFO $2\033[0m"
+            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[32m[INFO] $2\033[0m"
             ;;
         warn)
-            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[33mWARN $2\033[0m"
+            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[33m[WARN] $2\033[0m"
             ;;
         error)
-            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[31mERROR $2\033[0m"
+            echo -e "\033[36m$TIMESTAMP\033[0m $SOURCE \033[31m[ERROR] $2\033[0m"
             ;;
         *) ;;
     esac
 }
 
 function install() {
-    local configFile=$1
-    ansible-playbook -e "@$configFile" -i $SCRIPT_DIR/test.sh  $SCRIPT_DIR/playbooks/test.yml
+    ansible-playbook -e "@$CONFIG_FILE" -i "$INVENTORY_FILE" $SCRIPT_DIR/playbooks/test.yml
 }
 
 ### Main Lines ##################################################
@@ -50,19 +53,25 @@ function main() {
   # check bash shell
   readlink /proc/$$/exe|grep -q "bash" || { logger error "you should use bash shell only"; exit 1; }
 
-  # check 'ansible' executable
+  # check 'ansible-playbook' executable
   which ansible > /dev/null 2>&1 || { logger error "need 'ansible', try: 'pip install ansible'"; usage; exit 1; }
 
-  [ "$#" -gt 0 ] || { usage >&2; exit 2; }
+  # check config file
+  [ "$#" -eq 2 ] || { usage >&2; exit 1; }
+  CONFIG_FILE=$2
+  [ ! -e $CONFIG_FILE ] && { logger error "config file [ $CONFIG_FILE ] not exist"; exit 1; }
+
+  # check inventory file
+  INVENTORY_FILE=$(awk '/  inventory:/ {gsub(/["'\'']/, "", $NF); print $NF}' $CONFIG_FILE)
+  [ ! -e $INVENTORY_FILE ] && { logger error "inventory file [ $INVENTORY_FILE ] not exist"; exit 1; }
 
   case "$1" in
       (install)
-          [ "$#" -eq 2 ] || { usage >&2; exit 2; }
-          install "${@:2}"
+          install
           ;;
       (*)
           usage
-          exit 0
+          exit 1
           ;;
   esac
 }
